INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlogard 10mg Tablet', 185.6, 'Pfizer Ltd', 'strip of 30 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('App.UP Plus Syrup', 137, 'Intas Pharmaceuticals Ltd', 'bottle of 200 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Altime CF Syrup Sugar Free', 101, 'S H Pharmaceuticals Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Altonil Plus 3 Tablet', 52, 'Alteus Biogenics Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Actapro Tablet', 120, 'Sun Pharmaceutical Industries Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Asklerol 3% Injection', 146.79, 'Samarth Life Sciences Pvt Ltd', 'vial of 2 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlopin-AT Tablet', 85.5, 'USV Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alpracon 0.5mg Tablet', 34.85, 'Icon Pharma & Surgicals Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alex P Paed Drop', 73, 'Glenmark Pharmaceuticals Ltd', 'bottle of 15 ml Drop');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acuclav IV 1.2gm Injection', 152.65, 'Macleods Pharmaceuticals Pvt Ltd', 'vial of 1 Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alcinac-PG Forte Tablet SR', 195, 'Leeford Healthcare Ltd', 'strip of 10 tablet sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorfit CV 10 Capsule', 297, 'Ajanta Pharma Ltd', 'strip of 15 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Accutaz PS 250mg/31.25mg Injection', 55, 'Macleods Pharmaceuticals Pvt Ltd', 'vial of 1 Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aplev M 5mg/10mg Tablet', 95, 'Ajanta Pharma Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acolate LP 2.5mg/10mg Tablet', 44, 'Gujarat Terce Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amt 25mg Tablet', 24, 'Mahendra Labs Private Limited', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ambrolite-S Expectorant', 106, 'Tablets India Limited', 'bottle of 100 ml Expectorant');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('AZR Tablet', 118.23, 'Ipca Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlopres 2.5 Tablet', 30.03, 'Cipla Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azid 250mg Tablet', 66.08, 'Indi Pharma', 'strip of 6 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azunate 60mg Injection', 208.24, 'Macleods Pharmaceuticals Pvt Ltd', 'vial of 1 Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aceloflam Plus Tablet', 94, 'Alkem Laboratories Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Abitol Tablet', 12.4, 'Lincoln Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alrax 25mg Tablet', 33, 'SG Lifecare Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Actifed DM  Syrup', 72.6, 'Glaxo SmithKline Pharmaceuticals Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlozaar Tablet', 249, 'Micro Labs Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aldactone 100 Tablet', 211.05, 'RPG Life Sciences Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alkof AP Plus Syrup', 92, 'Alkem Laboratories Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Agoprex Tablet', 149, 'Sun Pharmaceutical Industries Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anaero Gel', 180, 'Amwill Healthcare', 'tube of 25 gm Gel');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arifix 200mg Tablet DT', 99, 'Sarian Healthcare', 'strip of 10 tablet dt');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amrfy 0.25% Cream', 350, 'Hegde and Hegde Pharmaceutical LLP', 'tube of 30 gm Cream');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amiseven 7% Injection', 621, 'Hospimax Healthcare Pvt Ltd', 'vial of 250 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('AB Day 200mg Capsule SR', 136, 'Isis Healthcare Pvt Ltd', 'strip of 10 capsule sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atp 0.6mg Injection', 5.99, 'Biomiicron Pharmaceuticals', 'vial of 1 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Altime LS Syrup', 85, 'S H Pharmaceuticals Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Agmamol 500mg Tablet', 14, 'Amore Health Essentials Pvt Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atarax Syrup', 110.25, 'Dr Reddy''s Laboratories Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adalipca 40mg Injection', 15000, 'Ipca Laboratories Ltd', 'vial of 1 Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acefenac 100mg Tablet', 24.3, 'Medichem Pharmceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azeldip 16 Tablet', 153, 'Glenmark Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('AD 10mg Sachet', 13.2, 'Hetero Drugs Ltd', 'packet of 1 gm Sachet');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alivher ES Tablet', 218, 'Akumentis Healthcare Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acenomac 1 Tablet', 59.4, 'Macleods Pharmaceuticals Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amoxyclav 375 Tablet', 356.92, 'Abbott', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acimol 200mg Tablet SR', 45, 'Leeford Healthcare Ltd', 'strip of 10 tablet sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amaryl 4mg Tablet', 397, 'Sanofi India  Ltd', 'strip of 30 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alevo 500 Tablet', 100.24, 'Alkem Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adiflam 1% Gel', 37, 'Leben Life Sciences Pvt Ltd', 'tube of 30 gm Gel');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arpizol 30 Tablet', 316, 'Sun Pharmaceutical Industries Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amikacin Sulphate 500mg Injection', 11.87, 'Sun Pharmaceutical Industries Ltd', 'vial of 2 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anovate Cream', 134.2, 'USV Ltd', 'tube of 20 gm Cream');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amrolfin Cream', 499, 'Skinska Pharmaceutica Pvt Ltd', 'tube of 50 gm Cream');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amitril 25mg Tablet', 16.8, 'Sigmund Promedica', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ambrodil-D Junior Syrup', 48.87, 'Aristo Pharmaceuticals Pvt Ltd', 'bottle of 60 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adoclear HQ Cream', 2992, 'Adonis Laboratories Pvt Ltd', 'bottle of 50 ml Cream');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atropine 1% Eye Drop', 39.94, 'Jawa Pharmaceuticals  Pvt Ltd', 'packet of 10 ml Eye Drop');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arolson Cream', 160, 'Unison Pharmaceuticals Pvt Ltd', 'tube of 30 gm Cream');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acebro 100mg Tablet', 100, 'Mediyork Pharma Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alcipro 250mg Tablet', 23.28, 'Alkem Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Apetiz Syrup', 34.72, 'Meridian Medicare Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alzam 0.5mg Tablet', 21, 'Midas Healthcare Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aziwok 500 Tablet', 132.36, 'Dr Reddy''s Laboratories Ltd', 'strip of 5 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acton Prolongatum 60IU Injection', 2141.26, 'Ferring Pharmaceuticals', 'vial of 5 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amantex Tablet', 215, 'Intas Pharmaceuticals Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adlumab 40mg Injection', 25000, 'RPG Life Sciences Ltd', 'vial of 0.8 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Akostol-OD Tablet SR', 250, 'Zydus Cadila', 'strip of 10 tablet sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acera-D Capsule SR', 118.45, 'Ipca Laboratories Ltd', 'strip of 10 capsule sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aqua Plus Eye Drop', 18, 'J B Chemicals and Pharmaceuticals Ltd', 'packet of 10 ml Eye Drop');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arthopan 500mg Tablet', 113.71, 'Crescent Therapeutics Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anoliv 300mg Tablet', 299, 'Arvincare Pharma', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Asar-CT 40/12.5 Tablet', 153, 'Glenmark Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aprizol 5mg Tablet', 38.5, 'Sain Medicaments Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlozaar Tablet', 166, 'Micro Labs Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Armist Nasal Spray', 259, 'Ordain Health Care Global Pvt Ltd', 'bottle of 9.8 ml Nasal Spray');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Apeton Plus Syrup', 56.25, 'Olcare Laboratories', 'bottle of 200 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adilip 45 Tablet DR', 97, 'Intas Pharmaceuticals Ltd', 'strip of 10 Tablet DR');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acebronk MFX 10mg/120mg/200mg Tablet', 175, 'Citizen Remedies Private Limited', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aggribloc 5mg Infusion', 5748.1, 'Abbott', 'bottle of 100 ml Infusion');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Afderm-MN + Cream', 130.9, 'Anglo-French Drugs & Industries Ltd', 'tube of 15 gm Cream');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arzep Nasal Spray', 472.45, 'Zydus Cadila', 'packet of 10 ml Nasal Spray');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amoxyplus-CV 625 LB Tablet', 154, 'Symbiosis Lab', 'strip of 6 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anti Cold Tablet', 70, 'Safe Life Care', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azro 500 Tablet', 66.35, 'Abbott', 'strip of 3 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Antiworm 400mg Tablet', 10.95, 'Hi Tech Pharmaceuticals Pvt Ltd', 'strip of 1 Tablet');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alba 400mg Tablet', 13.54, 'Life Medicare & Biotech Pvt Ltd', 'strip of 1 Tablet');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlodac M 25 Tablet PR', 108.5, 'Zydus Cadila', 'strip of 15 Tablet pr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Apexitra SB 65 Capsule', 140, 'Apex Laboratories Pvt Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Agidol Plus 1.5mg Tablet', 34.66, 'AGM Biotec', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aztel Trio 40mg/5mg/12.5mg Tablet', 72, 'Azkka Pharmaceuticals Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ace Plus Tablet', 99, 'Maxis Healthcare', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alpred 4mg Tablet', 52, 'Allenge India', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Abpress PF Eye Drop', 437.5, 'Entod Pharmaceuticals Ltd', 'bottle of 10 ml Eye Drop');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Abd 400mg Tablet', 9.58, 'Intas Pharmaceuticals Ltd', 'strip of 1 Tablet');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Advacan 0.25mg Tablet', 531, 'Biocon', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azibact 100 Readymix Oral Suspension', 47.65, 'Ipca Laboratories Ltd', 'bottle of 15 ml Oral Suspension');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azoran Tablet', 236.25, 'RPG Life Sciences Ltd', 'strip of 20 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('ATR-F Tablet', 137, 'Knoll Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arden 650mg Tablet', 28.06, 'Adonis Laboratories Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acesoft-SP Tablet', 75, 'Innovexia Life Sciences Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anprox-MR Tablet', 35, 'Seagull Pharmaceutical Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acefen P 100 mg/500 mg Tablet', 38, 'Salud Care India Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acitrom 2 Tablet', 414.65, 'Abbott', 'strip of 30 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acutret 10 Capsule', 205.5, 'Ipca Laboratories Ltd', 'strip of 10 soft gelatin capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alerkim 0.5mg Tablet', 3.9, 'Kim Lab', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Albamine 100mcg Tablet', 12.55, 'Albus Healthcare Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Avillin 25mg Injection', 32.2, 'Admac Pharma Ltd', 'vial of 1 Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alona Plus Tablet', 44, 'Serwina Pharmaceuticals Private Limited', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Asthagrip DM Tablet', 299, 'Druto Laboratories', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('A Plus 100mg/500mg Tablet', 40, 'Medmex Health Care', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alprax Forte 0.5 mg/50 mg Tablet', 99.6, 'Torrent Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('ALKAFRESH SYRUP', 60, 'Smart Laboratories Pvt Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Avil Advance Tablet', 20, 'Sanofi India  Ltd', 'strip of 5 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anglocet Tablet', 1.98, 'Anglo-French Drugs & Industries Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anafortan-MF 50mg/250mg Tablet', 93.09, 'Abbott', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alfatam-D Tablet MR', 235.5, 'Zydus Cadila', 'strip of 10 tablet mr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arbitel-CT 40 Tablet', 118, 'Micro Labs Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ace-Proxyvon CR Tablet', 143.25, 'Dr Reddy''s Laboratories Ltd', 'strip of 10 tablet cr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acera-L Capsule SR', 217.6, 'Ipca Laboratories Ltd', 'strip of 10 capsule sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('ATZ 50 Tablet', 118.23, 'Intas Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('A2  Tablet', 66.58, 'Medley Pharmaceuticals', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Addwize OD 18mg Tablet', 180, 'Sun Pharmaceutical Industries Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Airol Cream', 105, 'Abbott', 'tube of 20 gm Cream');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aminophylline 250mg Injection', 20.04, 'Harson Laboratories', 'ampoule of 10 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aerotrop Inhalation', 173.2, 'Macleods Pharmaceuticals Pvt Ltd', 'strip of 15 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Avanext 200 Tablet', 733.7, 'Zydus Cadila', 'strip of 4 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adiflam Plus 400 mg/500 mg Tablet', 19.5, 'Leben Life Sciences Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alsita-M 50 Forte IR Tablet', 92, 'Alkem Laboratories Ltd', 'strip of 10 tablet ir');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Albid 400mg Tablet', 8.3, 'Shine Pharmaceuticals Ltd', 'strip of 1 Tablet');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Almox 250 Capsule', 37.08, 'Alkem Laboratories Ltd', 'strip of 15 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Almocef O 200 mg/200 mg Tablet', 155, 'Gujarat Terce Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Angicam-Beta Tablet', 37, 'Blue Cross Laboratories Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aziwin 500 Tablet', 78.5, 'Bal Pharma Ltd', 'strip of 3 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Airmont-L Tablet', 90, 'Intra Labs India Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amclox Capsule', 69.02, 'Walter Bushnell', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('ACE P  TABLET 100 MG/325 MG', 30.55, 'Zee Laboratories', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorec-ASP Capsule', 34.85, 'Emcure Pharmaceuticals Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlopin 10 Tablet', 63.06, 'USV Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aginal 5 Tablet', 48.54, 'Alembic Pharmaceuticals Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aten-H 12.5 Tablet', 97.22, 'Zydus Cadila', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('ACTION OR 1000mg Tablet', 42.3, 'Apex Laboratories Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azobat 500mg Tablet', 59.58, 'Intra Life', 'strip of 3 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ark-TH4 Tablet', 184.1, 'Apex Laboratories Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ablif LB 200mg Tablet', 175, 'Pharma Plus', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Almox 500 Capsule', 80.26, 'Alkem Laboratories Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acnilite Gel', 127, 'Velite Pharmaceuticals', 'tube of 20 gm Gel');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Allercet-L Tablet', 59, 'Micro Labs Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acetal SP 100 mg/500 mg/15 mg Tablet', 54.68, 'Total Healthcare', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amitin 10mg Tablet', 16.5, 'Mission Research Laboratories Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('AL 5mg Tablet', 29.5, 'Avancer Labs Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atonide Gel', 125, 'Curatio Healthcare India Pvt Ltd', 'tube of 20 gm Gel');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alzero M Tablet', 228, 'Indchemie Health Specialities Pvt Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Avacard 5mg Tablet', 29.23, 'Sun Pharmaceutical Industries Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aceked-SP Tablet', 85, 'Orlife Healthcare', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Augpen -DS Suspension', 149.7, 'Zuventus Healthcare Ltd', 'bottle of 30 ml Suspension');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azacort 6 Tablet', 71.42, 'Three Dots Lifescience', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Astharid Plus Tablet', 20, 'Empiai Pharmaceuticals Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acemol SP 100mg/325mg/15mg Tablet', 93, 'Positive Medicare Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Asthakind-DX Syrup Sugar Free', 95.7, 'Mankind Pharma Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amitryn 10 Tablet', 25.5, 'KC Laboratories', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anprox Tablet', 31.46, 'Seagull Pharmaceutical Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ariday 2.5 Tablet', 41, 'Linux Laboratories', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alday AM Tablet SR', 60.6, 'S H Pharmaceuticals Ltd', 'strip of 10 Tablet pr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azeldip 8mg Tablet', 100.5, 'Glenmark Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aztor 40 Tablet', 1299.53, 'Sun Pharmaceutical Industries Ltd', 'bottle of 90 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alakast FA 10mg/120mg/200mg Tablet', 279, 'Avel Life Sciences', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aptirich Syrup', 58, 'Depsons Pharma', 'bottle of 200 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Apitat Syrup', 85, 'Lupin Ltd', 'bottle of 200 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Augpen 80mg/11.4mg Drop', 105.7, 'Zuventus Healthcare Ltd', 'packet of 10 ml Drop');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Abmont LC 5mg/10mg Tablet', 135, 'Matrixx Formulation', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alde Plus Tablet', 119, 'HS Aldem Healthcare', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atecard 50 Tablet', 31.04, 'Alembic Pharmaceuticals Ltd', 'strip of 14 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlace Tablet', 91.57, 'USV Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Activert 16mg Tablet', 75, 'Univentis Medicare Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azikind 250mg Tablet', 71.37, 'Mankind Pharma Ltd', 'strip of 6 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Axifur 500mg Tablet', 338.7, 'Veritaz Healthcare Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acura Gel', 220, 'Parry Pharma Pvt Ltd', 'tube of 15 gm Gel');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ascodex D Syrup', 129, 'Glenmark Pharmaceuticals Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amoxycillin 125mg Syrup', 24.5, 'Lark Laboratories Ltd', 'bottle of 60 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Advent 625 Tablet', 223.44, 'Cipla Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlong-A Tablet', 145, 'Micro Labs Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlopin-M Tablet PR', 118.5, 'USV Ltd', 'strip of 10 Tablet pr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorva 20 Tablet', 247.78, 'Zydus Cadila', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acivir Eye Ointment', 58.11, 'Cipla Ltd', 'tube of 5 gm Eye Ointment');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azom 500mg Injection', 324.5, 'United Biotech Pvt Ltd', 'vial of 1 Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amaryl M  2mg Tablet PR', 363.34, 'Sanofi India  Ltd', 'strip of 20 Tablet pr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Almefkem-D Tablet', 130, 'Alkem Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Asunra 400mg Tablet', 827, 'Novartis India Ltd', 'strip of 6 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azel 80 Capsule', 8700, 'Dr Reddy''s Laboratories Ltd', 'strip of 14 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Allergin 10mg Tablet', 95, 'Jenburkt Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aclofen Plus Tablet', 11, 'Ind Swift Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amleod 5mg Tablet', 24.46, 'Knoll Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ambrox T Syrup', 50, 'Bajaj Pharmaceutical', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amoxil 500mg Injection', 23.52, 'Zydus Healthcare Limited', 'vial of 2 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azax 500 Tablet', 79.3, 'Sun Pharmaceutical Industries Ltd', 'strip of 3 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adilan 40mg Tablet SR', 102.76, 'Albert David Ltd', 'strip of 10 tablet sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Asar 40 Tablet', 109, 'Glenmark Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aldigesic Injection', 21, 'Alkem Laboratories Ltd', 'vial of 1 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorlip-ASP 20 Capsule', 40.24, 'Cipla Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acefile P 100mg/325mg Tablet', 66.25, 'Ajanta Pharma Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aftron Tablet', 103.4, 'Astraea Life Sciences Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Algesia P 100 mg/500 mg Tablet', 59.8, 'Macleods Pharmaceuticals Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arthocerin-G Tablet', 167, 'Pulse Pharmaceuticals', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ace-Proxyvon SP Tablet', 123, 'Dr Reddy''s Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorva Asp 75 Capsule', 44.35, 'Zydus Cadila', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Albendazole 400mg Tablet', 9.58, 'Cadila Pharmaceuticals Ltd', 'strip of 1 Tablet');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Augxetil 500mg Tablet', 383, 'Koye Pharmaceuticals Pvt ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Airtec FB 400 Instacap', 239.9, 'Glenmark Pharmaceuticals Ltd', 'bottle of 30 instacaps');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlip 5 Tablet', 32.36, 'Cipla Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azovas T 40 Tablet', 153.93, 'J B Chemicals and Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Actacrez 2.25g Injection', 874, 'Fusion Healthcare Pvt Ltd', 'vial of 1 Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alto''s Citrasol Liquid', 54, 'Alto Healthcare Pvt. Ltd.', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Avemime HT Cream', 94, 'Avancer Labs Pvt Ltd', 'tube of 15 gm Cream');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ancool  SF Suspension', 173.6, 'Zuventus Healthcare Ltd', 'bottle of 200 ml Suspension');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azicare 500mg Tablet', 147.8, 'Olcare Laboratories', 'strip of 6 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anawin 0.5% Injection', 95.8, 'Neon Laboratories Ltd', 'vial of 20 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Analiv 500 Tablet', 170, 'Systopic Laboratories Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azuvas-F 20 Tablet', 119.9, 'Azkka Pharmaceuticals Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alprax 0.5mg Tablet', 66.9, 'Torrent Pharmaceuticals Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atrox 150mg Tablet', 65, 'Zota Health care Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Abrophyll-DM Tablet', 300, 'Vivid Biotek Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ampoxin 500 Capsule', 88.9, 'Torrent Pharmaceuticals Ltd', 'strip of 15 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Actifed 25 mg/2.5 mg Tablet', 6.5, 'Glaxo SmithKline Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alzero D Tablet', 88, 'Indchemie Health Specialities Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adiza Tablet', 139.08, 'Abbott', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('ALERGIN L TABLET', 45, 'Cipla Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aquazide 12.5 Tablet', 12.15, 'Sun Pharmaceutical Industries Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aphexine 200mg Tablet', 100.9, 'Ajanta Pharma Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorbest 10 Tablet', 68.21, 'Cadila Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acnetor AD Gel', 350.5, 'Torrent Pharmaceuticals Ltd', 'tube of 15 gm Gel');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlong-H Tablet', 115, 'Micro Labs Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azikem 200mg/5ml Suspension', 51.7, 'Alkem Laboratories Ltd', 'bottle of 15 ml Suspension');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alerid Cold Tablet', 65.5, 'Cipla Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Asthalin Rotacaps', 21.62, 'Cipla Ltd', 'packet of 30 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amlokind Beta 5mg/25mg Tablet PR', 62, 'Mankind Pharma Ltd', 'strip of 10 Tablet pr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Airtab-FX Tablet', 69, 'Systopic Laboratories Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acemyoset P Tablet', 189, 'Sparsh Remedies Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ascodex DX Syrup', 71, 'Glenmark Pharmaceuticals Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alprax Z 0.25 mg/3 mg Tablet', 19.72, 'Torrent Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Abvida-M 50mg/500mg Eazy Glide Tablet', 217.75, 'Abbott', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azulix 3 Tablet', 142.85, 'Torrent Pharmaceuticals Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amtas-E Tablet', 155, 'Intas Pharmaceuticals Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aclopride SP 100 mg/500 mg/15 mg Tablet', 66.21, 'Innovative Pharmaceuticals', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alinfec 500mg Injection', 58, 'Abbott', 'vial of 2 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorsave CV 20 Capsule', 157.86, 'Eris Lifesciences Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Avas CV 20 Capsule', 148, 'Micro Labs Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Augmentin DDS Suspension', 173, 'Glaxo SmithKline Pharmaceuticals Ltd', 'bottle of 30 ml Oral Suspension');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alkepin Odt 25mg Tablet', 31.2, 'Alkem Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Afogatran 150 Capsule', 398, 'Torrent Pharmaceuticals Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Allercet-M Syrup', 104, 'Micro Labs Ltd', 'bottle of 60 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acceclowoc-SP Tablet', 121.1, 'Tridoss Laboratories Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aciloc Injection', 6.03, 'Cadila Pharmaceuticals Ltd', 'vial of 2 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amity 10mg Tablet', 21.3, 'Chemo Healthcare Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorsave Gold 75mg/10mg/75mg Capsule', 58.6, 'Eris Lifesciences Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Almotan 6.25 Tablet', 211, 'MSN Laboratories', 'strip of 4 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Adgaba Gel', 236, 'Bion Therapeutics India Pvt Ltd', 'tube of 30 gm Gel');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arbitel 20 Tablet', 40.99, 'Micro Labs Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alsartan-H Tablet', 91.95, 'Aristo Pharmaceuticals Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aquaray Plus  Eye Drop', 495, 'Raymed Pharmaceuticals Ltd', 'bottle of 10 ml Eye Drop');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorlip CV 20 Capsule', 206.1, 'Cipla Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arigaba 100 Tablet', 74.66, 'Arinna Lifescience Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alltop 0.25mg Tablet', 1.76, 'Ind Swift Laboratories Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alphaday Tablet', 399, 'Intra Life', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorec Gold 20 Capsule', 64.8, 'Emcure Pharmaceuticals Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('AB-Flo Capsule', 156.6, 'Lupin Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acimol-SP Tablet', 65, 'Leeford Healthcare Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ambrodil-S Plus Syrup', 55, 'Aristo Pharmaceuticals Pvt Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acendol-P Tablet', 59.2, 'Serum Institute Of India Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Arixtra 2.5mg Injection', 680, 'Glaxo SmithKline Pharmaceuticals Ltd', 'vial of 0.5 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Aeovit-Q10 Softgel Capsule', 675, 'Aeobury Healthcare Pvt Ltd', 'strip of 10 soft gelatin capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ascodex BR Syrup', 52.5, 'Glenmark Pharmaceuticals Ltd', 'bottle of 60 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atracurium Besilate Injection', 185.31, 'Sun Pharmaceutical Industries Ltd', 'vial of 1 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ace-TH 4 Tablet', 175, 'Snu Biocare', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Allegra 180mg Tablet', 251.2, 'Sanofi India  Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Abevia 100 Capsule', 95, 'Mankind Pharma Ltd', 'strip of 10 capsules');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acamprol Tablet', 105.5, 'Sun Pharmaceutical Industries Ltd', 'strip of 6 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atorsave 20 Tablet', 247.8, 'Eris Lifesciences Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alrista 50mg Tablet', 96.8, 'Macleods Pharmaceuticals Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Atrodex-C Eye Drop', 157.12, 'Jawa Pharmaceuticals  Pvt Ltd', 'bottle of 5 ml Eye Drop');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amrizol-DSR Capsule', 135, 'Nuorik Healthcare', 'strip of 10 capsule sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amrox-LS Oral Drops', 70, 'Leeford Healthcare Ltd', 'bottle of 15 ml Oral Drops');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('ARAVON TABLET', 471.58, 'Sun Pharmaceutical Industries Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amaryl 3mg Tablet', 438.43, 'Sanofi India  Ltd', 'strip of 30 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ascapil 12A Tablet DT', 44.17, 'Abbott', 'strip of 1 Tablet DT');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Anin 500mg Injection', 328.5, 'Ind Swift Laboratories Ltd', 'vial of 2 ml Injection');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Asthalin 100mcg Inhaler', 157.85, 'Cipla Ltd', 'packet of 200 MDI Inhaler');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amaryl MV 2mg Tablet SR', 213.42, 'Sanofi India  Ltd', 'strip of 15 tablet sr');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('AT SP Tablet', 62, 'Atopic Laboratories', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ambulex M Tablet', 60.9, 'Unimarck Healthcare Ltd', 'strip of 15 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Albutamol Syrup', 65.4, 'Centaur Pharmaceuticals Pvt Ltd', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Azikem 500mg Tablet', 71.7, 'Alkem Laboratories Ltd', 'strip of 3 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Acneclin Gel', 36.2, 'Themis Medicare Ltd', 'tube of 10 gm Gel');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Amilip 5mg Tablet', 231, 'Bion Therapeutics India Pvt Ltd', 'strip of 50 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Alkaliser Syrup', 45, 'Life Sciences Inc', 'bottle of 100 ml Syrup');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('AVENE (ABBOTT) 0.5mg/10mg Tablet', 36, 'Abbott', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Auradex 4mg Tablet', 40, 'Aureate Healthcare Pvt Ltd', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Ampilox Kid  125 mg/125 mg Tablet', 42.35, 'Biochem Pharmaceutical Industries', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Akme CT 10 Tablet', 16.5, 'Akme Biotec', 'strip of 10 tablets');
INSERT INTO catalog (product_name, price, company, pack_size) VALUES ('Artilage  Tablet', 201, 'Wallace Pharmaceuticals Pvt Ltd', 'strip of 10 tablets');
